# Global settings applied to the whole site.
[build]
  base    = "."
  publish = "site"
  command = "./netlify.sh"

[context.production]
  command = "./netlify.sh production"

# Deploy Preview context: All Deploy Previews
# will inherit these settings.
[context.deploy-preview]
  command = "./netlify.sh preview"